services:
  postgres-db:
    container_name: potato_project
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: potato
      POSTGRES_PASSWORD: potato
      POSTGRES_DB: potato
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5432:5432"