CREATE TABLE potato_entity
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                       VARCHAR(255),
    hourly_pay                 DOUBLE PRECISION                        NOT NULL,
    hours_per_week             DOUBLE PRECISION                        NOT NULL,
    potato_price_at_conversion DOUBLE PRECISION                        NOT NULL,
    employment_type            VARCHAR(255),
    experience_level           VARCHAR(255),
    timestamp                  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_potato_entity PRIMARY KEY (id)
);