CREATE TABLE contribution_bracket
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    min_age             INTEGER                                 NOT NULL,
    max_age             INTEGER                                 NOT NULL,
    recommended_percent DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_contribution_bracket PRIMARY KEY (id)
);